### PR TITLE
#151000651 Integrate heroku

### PR DESCRIPTION
**Pull request by devGenie**
#### What does this PR do?
Prepares Heroku for deployment.
#### Description of Task to be completed?
Prepare online environments to deploy the project

#### What are the relevant pivotal tracker stories?
#151000651

### CODE REVIEW

**Review by collinmutembei — APPROVED** [review]
LGTM

**Comment by collinmutembei** [comment]
@briankabiro Add the whitenoise middleware changes to the branch on this PR and create a new PR.

**Comment by briankabiro** [comment]
@collinmutembei Do I need to do so now?

**Comment by collinmutembei** [comment]
@briankabiro I already did it

**Comment by briankabiro** [comment]
cool

**Pull request merged**
